opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-station-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${STATION_MYSQL_PASSWORD:Abcd1234#}
    url: jdbc:mysql://${STATION_MYSQL_HOST:ts-station-mysql}:${STATION_MYSQL_PORT:3306}/${STATION_MYSQL_DATABASE:ts-station-mysql}?useSSL=false
    username: ${STATION_MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
swagger:
  controllerPackage: fdse.microservice
