opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-travel2-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${TRAVEL2_MYSQL_PASSWORD:Abcd1234#}
    url: jdbc:mysql://${TRAVEL2_MYSQL_HOST:ts-travel2-mysql}:${TRAVEL2_MYSQL_PORT:3306}/${TRAVEL2_MYSQL_DATABASE:ts-travel2-mysql}?useSSL=false
    username: ${TRAVEL2_MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
swagger:
  controllerPackage: travel2.controller
