apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: train-ticket
requires:
  - configs: ["mysql-deployment"]
build:
  platforms: ["linux/amd64"]
  local:
    concurrency: 16
    push: true
    useDockerCLI: false
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - image: ts-admin-basic-info-service
      context: ts-admin-basic-info-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-order-service
      context: ts-admin-order-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-route-service
      context: ts-admin-route-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-travel-service
      context: ts-admin-travel-service
      docker:
        dockerfile: Dockerfile
    - image: ts-admin-user-service
      context: ts-admin-user-service
      docker:
        dockerfile: Dockerfile
    - image: ts-assurance-service
      context: ts-assurance-service
      docker:
        dockerfile: Dockerfile
    - image: ts-auth-service
      context: ts-auth-service
      docker:
        dockerfile: Dockerfile
    - image: ts-avatar-service
      context: ts-avatar-service
      docker:
        dockerfile: Dockerfile
    - image: ts-basic-service
      context: ts-basic-service
      docker:
        dockerfile: Dockerfile
    - image: ts-cancel-service
      context: ts-cancel-service
      docker:
        dockerfile: Dockerfile
    - image: ts-config-service
      context: ts-config-service
      docker:
        dockerfile: Dockerfile
    - image: ts-consign-price-service
      context: ts-consign-price-service
      docker:
        dockerfile: Dockerfile
    - image: ts-consign-service
      context: ts-consign-service
      docker:
        dockerfile: Dockerfile
    - image: ts-contacts-service
      context: ts-contacts-service
      docker:
        dockerfile: Dockerfile
    - image: ts-delivery-service
      context: ts-delivery-service
      docker:
        dockerfile: Dockerfile
    - image: ts-execute-service
      context: ts-execute-service
      docker:
        dockerfile: Dockerfile
    - image: ts-food-delivery-service
      context: ts-food-delivery-service
      docker:
        dockerfile: Dockerfile
    - image: ts-food-service
      context: ts-food-service
      docker:
        dockerfile: Dockerfile
    - image: ts-gateway-service
      context: ts-gateway-service
      docker:
        dockerfile: Dockerfile
    - image: ts-inside-payment-service
      context: ts-inside-payment-service
      docker:
        dockerfile: Dockerfile
    - image: ts-news-service
      context: ts-news-service
      docker:
        dockerfile: Dockerfile
    - image: ts-notification-service
      context: ts-notification-service
      docker:
        dockerfile: Dockerfile
    - image: ts-order-other-service
      context: ts-order-other-service
      docker:
        dockerfile: Dockerfile
    - image: ts-order-service
      context: ts-order-service
      docker:
        dockerfile: Dockerfile
    - image: ts-payment-service
      context: ts-payment-service
      docker:
        dockerfile: Dockerfile
    - image: ts-preserve-other-service
      context: ts-preserve-other-service
      docker:
        dockerfile: Dockerfile
    - image: ts-preserve-service
      context: ts-preserve-service
      docker:
        dockerfile: Dockerfile
    - image: ts-price-service
      context: ts-price-service
      docker:
        dockerfile: Dockerfile
    - image: ts-rebook-service
      context: ts-rebook-service
      docker:
        dockerfile: Dockerfile
    - image: ts-route-plan-service
      context: ts-route-plan-service
      docker:
        dockerfile: Dockerfile
    - image: ts-route-service
      context: ts-route-service
      docker:
        dockerfile: Dockerfile
    - image: ts-seat-service
      context: ts-seat-service
      docker:
        dockerfile: Dockerfile
    - image: ts-security-service
      context: ts-security-service
      docker:
        dockerfile: Dockerfile
    - image: ts-station-food-service
      context: ts-station-food-service
      docker:
        dockerfile: Dockerfile
    - image: ts-station-service
      context: ts-station-service
      docker:
        dockerfile: Dockerfile
    - image: ts-ticket-office-service
      context: ts-ticket-office-service
      docker:
        dockerfile: Dockerfile
    - image: ts-train-food-service
      context: ts-train-food-service
      docker:
        dockerfile: Dockerfile
    - image: ts-train-service
      context: ts-train-service
      docker:
        dockerfile: Dockerfile
    - image: ts-travel-plan-service
      context: ts-travel-plan-service
      docker:
        dockerfile: Dockerfile
    - image: ts-travel-service
      context: ts-travel-service
      docker:
        dockerfile: Dockerfile
    - image: ts-travel2-service
      context: ts-travel2-service
      docker:
        dockerfile: Dockerfile
    - image: ts-ui-dashboard
      context: ts-ui-dashboard
      docker:
        dockerfile: Dockerfile
    - image: ts-user-service
      context: ts-user-service
      docker:
        dockerfile: Dockerfile
    - image: ts-verification-code-service
      context: ts-verification-code-service
      docker:
        dockerfile: Dockerfile
    - image: ts-voucher-service
      context: ts-voucher-service
      docker:
        dockerfile: Dockerfile
    - image: ts-wait-order-service
      context: ts-wait-order-service
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ts-order-service/deployment.yaml
    - ts-station-food-service/deployment.yaml
    - ts-notification-service/deployment.yaml
    - ts-food-delivery-service/deployment.yaml
    - ts-admin-order-service/deployment.yaml
    - ts-avatar-service/deployment.yaml
    - ts-basic-service/deployment.yaml
    - ts-delivery-service/deployment.yaml
    - ts-preserve-other-service/deployment.yaml
    - ts-verification-code-service/deployment.yaml
    - ts-admin-route-service/deployment.yaml
    - ts-admin-user-service/deployment.yaml
    - ts-consign-price-service/deployment.yaml
    - ts-route-service/deployment.yaml
    - ts-security-service/deployment.yaml
    - ts-user-service/deployment.yaml
    - ts-admin-basic-info-service/deployment.yaml
    - ts-assurance-service/deployment.yaml
    - ts-auth-service/deployment.yaml
    - ts-config-service/deployment.yaml
    - ts-consign-service/deployment.yaml
    - ts-contacts-service/deployment.yaml
    - ts-execute-service/deployment.yaml
    - ts-rebook-service/deployment.yaml
    - ts-admin-travel-service/deployment.yaml
    - ts-station-service/deployment.yaml
    - ts-train-food-service/deployment.yaml
    - ts-route-plan-service/deployment.yaml
    - ts-order-other-service/deployment.yaml
    - ts-preserve-service/deployment.yaml
    - ts-train-service/deployment.yaml
    - ts-ui-dashboard/deployment.yaml
    - ts-gateway-service/deployment.yaml
    - ts-food-service/deployment.yaml
    - ts-inside-payment-service/deployment.yaml
    - ts-news-service/deployment.yaml
    - ts-price-service/deployment.yaml
    - ts-seat-service/deployment.yaml
    - ts-ticket-office-service/deployment.yaml
    - ts-travel-plan-service/deployment.yaml
    - ts-cancel-service/deployment.yaml
    - ts-voucher-service/deployment.yaml
    - ts-wait-order-service/deployment.yaml
    - ts-travel-service/deployment.yaml
    - ts-travel2-service/deployment.yaml
    - ts-payment-service/deployment.yaml
portForward:
  - resourceType: service
    resourceName: ts-admin-basic-info-service
    port: 8080
  - resourceType: service
    resourceName: ts-admin-order-service
    port: 8080
  - resourceType: service
    resourceName: ts-admin-route-service
    port: 8080
  - resourceType: service
    resourceName: ts-admin-travel-service
    port: 8080
  - resourceType: service
    resourceName: ts-admin-user-service
    port: 8080
  - resourceType: service
    resourceName: ts-assurance-service
    port: 8080
  - resourceType: service
    resourceName: ts-auth-service
    port: 8080
  - resourceType: service
    resourceName: ts-avatar-service
    port: 8080
  - resourceType: service
    resourceName: ts-basic-service
    port: 8080
  - resourceType: service
    resourceName: ts-cancel-service
    port: 8080
  - resourceType: service
    resourceName: ts-config-service
    port: 8080
  - resourceType: service
    resourceName: ts-consign-price-service
    port: 8080
  - resourceType: service
    resourceName: ts-consign-service
    port: 8080
  - resourceType: service
    resourceName: ts-contacts-service
    port: 8080
  - resourceType: service
    resourceName: ts-delivery-service
    port: 8080
  - resourceType: service
    resourceName: ts-execute-service
    port: 8080
  - resourceType: service
    resourceName: ts-food-delivery-service
    port: 8080
  - resourceType: service
    resourceName: ts-food-service
    port: 8080
  - resourceType: service
    resourceName: ts-gateway-service
    port: 8080
  - resourceType: service
    resourceName: ts-inside-payment-service
    port: 8080
  - resourceType: service
    resourceName: ts-news-service
    port: 8080
  - resourceType: service
    resourceName: ts-notification-service
    port: 8080
  - resourceType: service
    resourceName: ts-order-other-service
    port: 8080
  - resourceType: service
    resourceName: ts-order-service
    port: 8080
  - resourceType: service
    resourceName: ts-payment-service
    port: 8080
  - resourceType: service
    resourceName: ts-preserve-other-service
    port: 8080
  - resourceType: service
    resourceName: ts-preserve-service
    port: 8080
  - resourceType: service
    resourceName: ts-price-service
    port: 8080
  - resourceType: service
    resourceName: ts-rebook-service
    port: 8080
  - resourceType: service
    resourceName: ts-route-plan-service
    port: 8080
  - resourceType: service
    resourceName: ts-route-service
    port: 8080
  - resourceType: service
    resourceName: ts-seat-service
    port: 8080
  - resourceType: service
    resourceName: ts-security-service
    port: 8080
  - resourceType: service
    resourceName: ts-station-food-service
    port: 8080
  - resourceType: service
    resourceName: ts-station-service
    port: 8080
  - resourceType: service
    resourceName: ts-ticket-office-service
    port: 8080
  - resourceType: service
    resourceName: ts-train-food-service
    port: 8080
  - resourceType: service
    resourceName: ts-train-service
    port: 8080
  - resourceType: service
    resourceName: ts-travel-plan-service
    port: 8080
  - resourceType: service
    resourceName: ts-travel-service
    port: 8080
  - resourceType: service
    resourceName: ts-travel2-service
    port: 8080
  - resourceType: service
    resourceName: ts-ui-dashboard
    port: 8080
  - resourceType: service
    resourceName: ts-user-service
    port: 8080
  - resourceType: service
    resourceName: ts-verification-code-service
    port: 8080
  - resourceType: service
    resourceName: ts-voucher-service
    port: 8080
  - resourceType: service
    resourceName: ts-wait-order-service
    port: 8080
deploy:
  kubectl: {}


---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mysql-deployment
manifests:
  rawYaml: 
  - manifests/kubectl/*.yaml
deploy:
  kubectl: {}
  # helm:
  #   releases:
  #     - name: mysql-operator
  #       chartPath: mysql-operator/mysql-operator
  #       namespace: mysql-operator
  #       createNamespace: true
  #       remote: true
  #       repo: https://mysql.github.io/mysql-operator/
  #       setValues: {}
  #     - name: mysql-cluster
  #       chartPath: mysql-operator/mysql-innodbcluster
  #       namespace: train-ticket
  #       createNamespace: true
  #       remote: true
  #       setValues:
  #         credentials.root.user: "root"
  #         credentials.root.password: "supersecret"
  #         credentials.root.host: "%"
  #         serverInstances: 3
  #         routerInstances: 1
