opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-admin-travel-service
swagger:
  controllerPackage: admintravel.controller
