opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-food-delivery-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${FOOD_DELIVERY_MYSQL_PASSWORD:root}
    url: jdbc:mysql://${FOOD_DELIVERY_MYSQL_HOST:ts-food-delivery-mysql}:${FOOD_DELIVERY_MYSQL_PORT:3306}/${FOOD_DELIVERY_MYSQL_DATABASE:ts-food-delivery-mysql}?useSSL=false
    username: ${FOOD_DELIVERY_MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
swagger:
  controllerPackage: fooddelivery.controller
