opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    gateway:
      routes:
      - id: admin-basic-info
        predicates:
        - Path=/api/v1/adminbasicservice/**
        uri: http://${ADMIN_BASIC_INFO_SERVICE_HOST:ts-admin-basic-info-service}
      - id: admin-order
        predicates:
        - Path=/api/v1/adminorderservice/**
        uri: http://${ADMIN_ORDER_SERVICE_HOST:ts-admin-order-service}
      - id: admin-route
        predicates:
        - Path=/api/v1/adminrouteservice/**
        uri: http://${ADMIN_ROUTE_SERVICE_HOST:ts-admin-route-service}
      - id: admin-travel
        predicates:
        - Path=/api/v1/admintravelservice/**
        uri: http://${ADMIN_TRAVEL_SERVICE_HOST:ts-admin-travel-service}
      - id: admin-user
        predicates:
        - Path=/api/v1/adminuserservice/users/**
        uri: http://${ADMIN_USER_SERVICE_HOST:ts-admin-user-service}
      - id: assurance
        predicates:
        - Path=/api/v1/assuranceservice/**
        uri: http://${ASSURANCE_SERVICE_HOST:ts-assurance-service}
      - id: auth
        predicates:
        - Path=/api/v1/auth/**
        uri: http://${AUTH_SERVICE_HOST:ts-auth-service}
      - id: auth-user
        predicates:
        - Path=/api/v1/users/**
        uri: http://${AUTH_SERVICE_HOST:ts-auth-service}
      - id: avatar
        predicates:
        - Path=/api/v1/avatar/**
        uri: http://${AVATAR_SERVICE_HOST:ts-avatar-service}
      - id: basic
        predicates:
        - Path=/api/v1/basicservice/**
        uri: http://${BASIC_SERVICE_HOST:ts-basic-service}
      - id: cancel
        predicates:
        - Path=/api/v1/cancelservice/**
        uri: http://${CANCEL_SERVICE_HOST:ts-cancel-service}
      - id: config
        predicates:
        - Path=/api/v1/configservice/**
        uri: http://${CONFIG_SERVICE_HOST:ts-config-service}
      - id: consign-price
        predicates:
        - Path=/api/v1/consignpriceservice/**
        uri: http://${CONSIGN_PRICE_SERVICE_HOST:ts-consign-price-service}
      - id: consign
        predicates:
        - Path=/api/v1/consignservice/**
        uri: http://${CONSIGN_SERVICE_HOST:ts-consign-service}
      - id: contacts
        predicates:
        - Path=/api/v1/contactservice/**
        uri: http://${CONTACTS_SERVICE_HOST:ts-contacts-service}
      - id: execute
        predicates:
        - Path=/api/v1/executeservice/**
        uri: http://${EXECUTE_SERVICE_HOST:ts-execute-service}
      - id: food
        predicates:
        - Path=/api/v1/foodservice/**
        uri: http://${FOOD_SERVICE_HOST:ts-food-service}
      - id: inside-payment
        predicates:
        - Path=/api/v1/inside_pay_service/**
        uri: http://${INSIDE_PAYMENT_SERVICE_HOST:ts-inside-payment-service}
      - id: notification
        predicates:
        - Path=/api/v1/notifyservice/**
        uri: http://${NOTIFICATION_SERVICE_HOST:ts-notification-service}
      - id: order-other
        predicates:
        - Path=/api/v1/orderOtherService/**
        uri: http://${ORDER_OTHER_SERVICE_HOST:ts-order-other-service}
      - id: order
        predicates:
        - Path=/api/v1/orderservice/**
        uri: http://${ORDER_SERVICE_HOST:ts-order-service}
      - id: payment
        predicates:
        - Path=/api/v1/paymentservice/**
        uri: http://${PAYMENT_SERVICE_HOST:ts-payment-service}
      - id: preserve-other
        predicates:
        - Path=/api/v1/preserveotherservice/**
        uri: http://${PRESERVE_OTHER_SERVICE_HOST:ts-preserve-other-service}
      - id: preserve
        predicates:
        - Path=/api/v1/preserveservice/**
        uri: http://${PRESERVE_SERVICE_HOST:ts-preserve-service}
      - id: price
        predicates:
        - Path=/api/v1/priceservice/**
        uri: http://${PRICE_SERVICE_HOST:ts-price-service}
      - id: rebook
        predicates:
        - Path=/api/v1/rebookservice/**
        uri: http://${REBOOK_SERVICE_HOST:ts-rebook-service}
      - id: route-plan
        predicates:
        - Path=/api/v1/routeplanservice/**
        uri: http://${ROUTE_PLAN_SERVICE_HOST:ts-route-plan-service}
      - id: route
        predicates:
        - Path=/api/v1/routeservice/**
        uri: http://${ROUTE_SERVICE_HOST:ts-route-service}
      - id: seat
        predicates:
        - Path=/api/v1/seatservice/**
        uri: http://${SEAT_SERVICE_HOST:ts-seat-service}
      - id: security
        predicates:
        - Path=/api/v1/securityservice/**
        uri: http://${SECURITY_SERVICE_HOST:ts-security-service}
      - id: station-food
        predicates:
        - Path=/api/v1/stationfoodservice/**
        uri: http://${STATION_FOOD_SERVICE_HOST:ts-station-food-service}
      - id: station
        predicates:
        - Path=/api/v1/stationservice/**
        uri: http://${STATION_SERVICE_HOST:ts-station-service}
      - id: train-food
        predicates:
        - Path=/api/v1/trainfoodservice/**
        uri: http://${TRAIN_FOOD_SERVICE_HOST:ts-train-food-service}
      - id: train
        predicates:
        - Path=/api/v1/trainservice/**
        uri: http://${TRAIN_SERVICE_HOST:ts-train-service}
      - id: travel2
        predicates:
        - Path=/api/v1/travel2service/**
        uri: http://${TRAVEL2_SERVICE_HOST:ts-travel2-service}
      - id: travel-plan
        predicates:
        - Path=/api/v1/travelplanservice/**
        uri: http://${TRAVEL_PLAN_SERVICE_HOST:ts-travel-plan-service}
      - id: travel
        predicates:
        - Path=/api/v1/travelservice/**
        uri: http://${TRAVEL_SERVICE_HOST:ts-travel-service}
      - id: user
        predicates:
        - Path=/api/v1/userservice/users/**
        uri: http://${USER_SERVICE_HOST:ts-user-service}
      - id: verification-code
        predicates:
        - Path=/api/v1/verifycode/**
        uri: http://${VERIFICATION_CODE_SERVICE_HOST:ts-verification-code-service}
    name: ts-gateway-service
  main:
    web-application-type: reactive
