opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-preserve-service
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: 5672
swagger:
  controllerPackage: preserve.controller
