opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-notification-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${NOTIFICATION_MYSQL_PASSWORD:root}
    url: jdbc:mysql://${NOTIFICATION_MYSQL_HOST:ts-notification-mysql}:${NOTIFICATION_MYSQL_PORT:3306}/${NOTIFICATION_MYSQL_DATABASE:ts-notification-mysql}?useSSL=false
    username: ${NOTIFICATION_MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.163.com
    password: ${email_password:GZKSCXHBOLKMCLDQ}
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    username: ${email_address:trainticket_notify@163.com}
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: 5672
swagger:
  controllerPackage: notification.controller
