# Valid values are "daemonset", "deployment", and "statefulset".
mode: "deployment"

presets:
  kubernetesEvents:
    enabled: false
  clusterMetrics:
    enabled: false

image:
  # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
  repository: otel/opentelemetry-collector-contrib

configMap:
  create: true

config:
  exporters:
    debug:
      verbosity: normal
    otlp:
      endpoint: "jaeger-collector.monitoring:4317"
      tls:
        insecure: false
    clickhouse:
      endpoint: tcp://10.10.10.88:9000?dial_timeout=10s&compress=lz4&username=default&password=password
      database: default
      ttl: 72h
      logs_table_name: otel_logs
      traces_table_name: otel_traces
      metrics_table_name: otel_metrics
      timeout: 5s
      retry_on_failure:
        enabled: true
        initial_interval: 5s
        max_interval: 30s
        max_elapsed_time: 300s
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
    memory_ballast: {}
  processors:
    batch:
      timeout: 5s
      send_batch_size: 100000
    memory_limiter: null
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: kube-prom-exporter
            scrape_interval: 10s
            static_configs:
              - targets:
                - prometheus-stack-prometheus-node-exporter.monitoring:9100
                - prometheus-stack-kube-state-metrics.monitoring:8080
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs: 
        exporters:
          - debug
          - clickhouse
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics: 
        exporters:
          - clickhouse
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - debug
          - clickhouse
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

# Adding entries to Pod /etc/hosts with HostAliases
# https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
hostAliases:
  - ip: "10.10.10.202"
    hostnames:
    - "worker1"
  - ip: "10.10.10.203"
    hostnames:
    - "worker2"
  - ip: "10.10.10.204"
    hostnames:
    - "worker3"