opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-train-food-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${TRAIN_FOOD_MYSQL_PASSWORD:root}
    url: jdbc:mysql://${TRAIN_FOOD_MYSQL_HOST:ts-train-food-mysql}:${TRAIN_FOOD_MYSQL_PORT:3306}/${TRAIN_FOOD_MYSQL_DATABASE:ts-train-food-mysql}?useSSL=false
    username: ${TRAIN_FOOD_MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
swagger:
  controllerPackage: trainFood.controller
