opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-basic-service
swagger:
  controllerPackage: fdse.microservice.controller
