opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
server:
  port: 8080
spring:
  application:
    name: ts-wait-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${WAIT_ORDER_MYSQL_PASSWORD:Abcd1234#}
    url: jdbc:mysql://${WAIT_ORDER_MYSQL_HOST:10.176.122.1}:${WAIT_ORDER_MYSQL_PORT:3306}/${WAIT_ORDER_MYSQL_DATABASE:ts}?useSSL=false
    username: ${WAIT_ORDER_MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
swagger:
  controllerPackage: waitorder.controller
