apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic_service.fullname" . }}-jaeger
  labels:
    {{- include "generic_service.labels" . | nindent 4 }}
    app: jaeger
    app.kubernetes.io/component: agent
spec:
  ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: agent-config
      port: 5778
      protocol: TCP
      targetPort: 5778
  clusterIP: None
  selector:
    {{- include "generic_service.selectorLabels" . | nindent 4 }}
    app: jaeger
    app.kubernetes.io/component: all-in-one