apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic_service.fullname" . }}-jaeger-query
  labels:
    {{- include "generic_service.labels" . | nindent 4 }}
    app: jaeger
    app.kubernetes.io/component: query
spec:
  type: NodePort
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      nodePort: {{ .Values.jaeger.queryNodePort }}
  selector:
    {{- include "generic_service.selectorLabels" . | nindent 4 }}
    app: jaeger
    app.kubernetes.io/component: all-in-one