apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger-query
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      nodePort: {{ .Values.jaeger.queryService.nodePort | default 32688 }}
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one