name: Build and Push Docker Images

on:
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        mvn clean package -Dmaven.test.skip=true

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: http://10.10.10.210 # 自建Harbor地址
        username: ${{ secrets.HARBOR_USERNAME }} # 存储在GitHub Secrets中的用户名
        password: ${{ secrets.HARBOR_PASSWORD }} # 存储在GitHub Secrets中的密码

    - name: Build and Push Docker Images
      run: |
        # 遍历所有子目录，查找Dockerfile并构建、推送
        for dir in $(find . -maxdepth 2 -type f -name Dockerfile -exec dirname {} \;); do
          echo "Building Docker image in directory: $dir"
          IMAGE_NAME=$(basename "$dir")
          docker build -t 10.10.10.210/library/$IMAGE_NAME:$GITHUB_SHA "$dir"
          docker push 10.10.10.210/library/$IMAGE_NAME:$GITHUB_SHA
        done