name: test-build-images

on:
  push:
    paths:
      - 'ts-*/**'
      - 'skaffold.yaml'
  workflow_dispatch:
jobs:
  build:
    name: test-build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true -T 1.5C
      
      - name: Build with Skaffold
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: build
